languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Atul Bhatt"
#logo = "img/logo.png"
description = "Portfolio"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Atul Bhatt"
  #image = "img/headshot.JPG"
  headline = "Java Developer"
  bio = ""
  links = [
      { email = "mailto:atulbhatt61@gmail.com" },
      { github = "https://github.com/Atul-Bhatt" },
  ]
